//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名:.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要用户名.
        /// </summary>
        public static string mbox_needName {
            get {
                return ResourceManager.GetString("mbox_needName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要密码.
        /// </summary>
        public static string mbox_needPassword {
            get {
                return ResourceManager.GetString("mbox_needPassword", resourceCulture);
            }
        }
    }
}
